import { sva } from "@styled-system/css";

export const headerRecipe = sva({
  slots: ["root", "left", "brand", "urlForm", "sizePicker"],
  base: {
    root: {
      position: "relative",
      alignItems: "stretch",
      background: "surface",
      color: "text",
      display: "grid",
      gridTemplateColumns: "1fr auto",
      justifyContent: "space-between",
      minHeight: "40",
      zIndex: "1000",
      boxShadow: "raised",
      smDown: {
        alignItems: "flex-start",
        flexDirection: "column",
        px: "12",
        py: "10",
      },
    },
    left: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyItems: "center",
      minWidth: "0",
      width: "full",
      height: "full",
      overflow: "hidden",
    },
    brand: {
      justifySelf: "center",
      textStyle: "mono.sm",
      fontWeight: "bold",
      textTransform: "uppercase",
      letterSpacing: "widest",
      mx: "4",
      outlineWidth: "[0px]",
      outlineStyle: "solid",
      outlineColor: "blue.90",
      transition: "[outline ease 0.75s]",
      _hover: {
        outlineWidth: "[20px]",
        outlineColor: "blue.50",
      },
    },
    urlForm: {
      alignItems: "center",
      background: "surface",
      borderStart: "default",
      display: "flex",
      minWidth: "224",
      height: "full",
      width: "full",
      smDown: {
        borderStart: "none",
      },
    },
    sizePicker: {
      alignItems: "center",
      display: "flex",
      gap: "12",
      justifyContent: "flex-end",
      px: "14",
      w: "fit",
      smDown: {
        gap: "10",
        justifyContent: "flex-start",
        pt: "8",
        px: "0",
        width: "full",
      },
    },
  },
});
